---
- name: Configure Cisco device with NETCONF/YANG and telemetry
  hosts: cisco01
  gather_facts: no
  tasks:

   - name: get IPS Cisco
     set_fact:
      source: "{{ lookup('community.general.dig', 'cisco01') }}"

   - name: show ip Cisco
     debug:
      msg: "{{ source }}"

   - name: get IPS of Telegraf node
     set_fact:
      telegraf_node: "{{ lookup('community.general.dig', 'controller') }}"

   - name: show ip Telegraf
     debug:
      msg: "{{ telegraf_node }}"

   # - name: configure telemetry
   #   cisco.ios.ios_config:
   #     lines:
   #      - netconf-yang
   #      - telemetry ietf subscription 2
   #      - encoding encode-kvgpb
   #      - filter xpath /ios-events-ios-xe-oper:interface-state-change
   #      - source-address "{{ source }}"
   #      - stream yang-notif-native
   #      - update-policy on-change
   #      - receiver ip address "{{ telegraf_node }}" 57000 protocol grpc-tcp

   - name: Netconf-yang
     cisco.ios.ios_config:
       lines:
        - netconf-yang
        - telemetry ietf subscription 2


   - name: configure telemetry
     cisco.ios.ios_config:
       lines:
        - encoding encode-kvgpb
        - filter xpath /ios-events-ios-xe-oper:interface-state-change
        - source-address {{ source }}
        - stream yang-notif-native
        - update-policy on-change
        - receiver ip address "{{ telegraf_node }}" 57000 protocol grpc-tcp
       parents: telemetry ietf subscription 2

